<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="MAIN" Id="{30828e1c-e934-40bb-9799-4da1a38f5c46}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[DoorControlLogic();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="16" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>